const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Flash: 0},
	{playerANIM: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{PlayerBox: 0},
	{Keyboard: 0},
	{Sine: 0},
	{Pickup: 0},
	{action: 0},
	{Enemy: 0},
	{EdgeMarker: 0},
	{txtScore: 0},
	{deathbox: 0},
	{DeathTxt: 0},
	{Text: 0},
	{score: 0},
	{lives: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	playerANIM: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	PlayerBox: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Pickup: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	EdgeMarker: class extends self.ISpriteInstance {},
	txtScore: class extends self.ITextInstance {},
	deathbox: class extends self.ISpriteInstance {},
	DeathTxt: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {}
}